name = "BipartiteGraphs"
uuid = "caf10ac8-0290-4205-88aa-f15908547e8d"
authors = ["Aayush Sabharwal <aayush.sabharwal@gmail.com>"]
version = "0.1.8"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[weakdeps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extensions]
BipartiteGraphsSparseArraysExt = "SparseArrays"

[compat]
DataStructures = "0.18, 0.19"
DocStringExtensions = "0.8, 0.9"
ExplicitImports = "1.13"
Graphs = "1.9"
PrecompileTools = "1"
SafeTestsets = "0.1, 1"
SciMLTesting = "1.4"
SparseArrays = "1"
Test = "1"
julia = "1.10"

[extras]
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SciMLTesting = "09d9d899-5365-40a9-917a-5f67fddea283"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ExplicitImports", "SafeTestsets", "SciMLTesting", "Test"]
