name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

concurrency:
  # Skip intermediate builds: always, but for the master branch.
  # Cancel intermediate builds: always, but for the master branch.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.refs != 'refs/tags/*'}}

jobs:
  build:
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    with:
      julia-version: "lts"
      debug-documenter: true
    secrets: "inherit"
