name: Downgrade
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'benchmark/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'benchmark/**'
jobs:
  test:
    if: false  # Disabled: downgrade tests need review. See issue for details.
    strategy:
      matrix:
        julia-version: ['1.10']
        group: ['InterfaceI']
    uses: "SciML/.github/.github/workflows/downgrade.yml@v1"
    with:
      julia-version: "${{ matrix.julia-version }}"
      group: "${{ matrix.group }}"
      skip: "Pkg,TOML"
      allow-reresolve: false
    secrets: "inherit"
